server:
  port: 8999
spring:
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    in-memory: true
    #如果此处设置为true，需要加activemq-pool依赖包，否则会自动配置失败，报JmsMessagingTemplate注入失败
    pool:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  configuration:
    aggressive-lazy-loading: true
  mapper-locations: mapper/**/*.xml
  type-aliases-package: com.gu.springdemo1.**.entity

